// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: zzstat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          string                 `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`           // "ATTACK", "DEFENSE", "HP", "CRIT_RATE", etc.
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "ADD", "MULTIPLY"
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                // Execution priority (e.g. 10=Base, 20=Add, 30=Multiply)
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                     // "base", "equipment", "buff", "skill"
	SourceId      string                 `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // e.g. "dragon_sword_0", "blessing_of_dragon"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatModifier) Reset() {
	*x = StatModifier{}
	mi := &file_zzstat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatModifier) ProtoMessage() {}

func (x *StatModifier) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatModifier.ProtoReflect.Descriptor instead.
func (*StatModifier) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{0}
}

func (x *StatModifier) GetStat() string {
	if x != nil {
		return x.Stat
	}
	return ""
}

func (x *StatModifier) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StatModifier) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatModifier) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *StatModifier) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StatModifier) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CalculateStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Modifiers     []*StatModifier        `protobuf:"bytes,2,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStatsRequest) Reset() {
	*x = CalculateStatsRequest{}
	mi := &file_zzstat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStatsRequest) ProtoMessage() {}

func (x *CalculateStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStatsRequest.ProtoReflect.Descriptor instead.
func (*CalculateStatsRequest) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateStatsRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CalculateStatsRequest) GetModifiers() []*StatModifier {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type CalculateStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalStats    map[string]float64     `protobuf:"bytes,1,rep,name=final_stats,json=finalStats,proto3" json:"final_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // e.g. {"HP": 5000, "ATTACK": 350, "DEFENSE": 200, "CRIT_RATE": 15}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStatsResponse) Reset() {
	*x = CalculateStatsResponse{}
	mi := &file_zzstat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStatsResponse) ProtoMessage() {}

func (x *CalculateStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStatsResponse.ProtoReflect.Descriptor instead.
func (*CalculateStatsResponse) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateStatsResponse) GetFinalStats() map[string]float64 {
	if x != nil {
		return x.FinalStats
	}
	return nil
}

var File_zzstat_proto protoreflect.FileDescriptor

const file_zzstat_proto_rawDesc = "" +
	"\n" +
	"\fzzstat.proto\x12\x06zzstat\"\xa7\x01\n" +
	"\fStatModifier\x12\x12\n" +
	"\x04stat\x18\x01 \x01(\tR\x04stat\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_id\x18\x06 \x01(\tR\bsourceId\"n\n" +
	"\x15CalculateStatsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x122\n" +
	"\tmodifiers\x18\x02 \x03(\v2\x14.zzstat.StatModifierR\tmodifiers\"\xa8\x01\n" +
	"\x16CalculateStatsResponse\x12O\n" +
	"\vfinal_stats\x18\x01 \x03(\v2..zzstat.CalculateStatsResponse.FinalStatsEntryR\n" +
	"finalStats\x1a=\n" +
	"\x0fFinalStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012^\n" +
	"\vStatService\x12O\n" +
	"\x0eCalculateStats\x12\x1d.zzstat.CalculateStatsRequest\x1a\x1e.zzstat.CalculateStatsResponseB=Z;github.com/singoesdeep/zzrpg/backend/internal/statclient/pbb\x06proto3"

var (
	file_zzstat_proto_rawDescOnce sync.Once
	file_zzstat_proto_rawDescData []byte
)

func file_zzstat_proto_rawDescGZIP() []byte {
	file_zzstat_proto_rawDescOnce.Do(func() {
		file_zzstat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zzstat_proto_rawDesc), len(file_zzstat_proto_rawDesc)))
	})
	return file_zzstat_proto_rawDescData
}

var file_zzstat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zzstat_proto_goTypes = []any{
	(*StatModifier)(nil),           // 0: zzstat.StatModifier
	(*CalculateStatsRequest)(nil),  // 1: zzstat.CalculateStatsRequest
	(*CalculateStatsResponse)(nil), // 2: zzstat.CalculateStatsResponse
	nil,                            // 3: zzstat.CalculateStatsResponse.FinalStatsEntry
}
var file_zzstat_proto_depIdxs = []int32{
	0, // 0: zzstat.CalculateStatsRequest.modifiers:type_name -> zzstat.StatModifier
	3, // 1: zzstat.CalculateStatsResponse.final_stats:type_name -> zzstat.CalculateStatsResponse.FinalStatsEntry
	1, // 2: zzstat.StatService.CalculateStats:input_type -> zzstat.CalculateStatsRequest
	2, // 3: zzstat.StatService.CalculateStats:output_type -> zzstat.CalculateStatsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zzstat_proto_init() }
func file_zzstat_proto_init() {
	if File_zzstat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zzstat_proto_rawDesc), len(file_zzstat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zzstat_proto_goTypes,
		DependencyIndexes: file_zzstat_proto_depIdxs,
		MessageInfos:      file_zzstat_proto_msgTypes,
	}.Build()
	File_zzstat_proto = out.File
	file_zzstat_proto_goTypes = nil
	file_zzstat_proto_depIdxs = nil
}
