// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: zzstat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          string                 `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`           // "ATTACK", "DEFENSE", "HP", "CRIT_RATE", etc.
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "ADD", "MULTIPLY"
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                // Execution priority (e.g. 10=Base, 20=Add, 30=Multiply)
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                     // "base", "equipment", "buff", "skill"
	SourceId      string                 `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // e.g. "dragon_sword_0", "blessing_of_dragon"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatModifier) Reset() {
	*x = StatModifier{}
	mi := &file_zzstat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatModifier) ProtoMessage() {}

func (x *StatModifier) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatModifier.ProtoReflect.Descriptor instead.
func (*StatModifier) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{0}
}

func (x *StatModifier) GetStat() string {
	if x != nil {
		return x.Stat
	}
	return ""
}

func (x *StatModifier) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StatModifier) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatModifier) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *StatModifier) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StatModifier) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CalculateStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Modifiers     []*StatModifier        `protobuf:"bytes,2,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStatsRequest) Reset() {
	*x = CalculateStatsRequest{}
	mi := &file_zzstat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStatsRequest) ProtoMessage() {}

func (x *CalculateStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStatsRequest.ProtoReflect.Descriptor instead.
func (*CalculateStatsRequest) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateStatsRequest) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CalculateStatsRequest) GetModifiers() []*StatModifier {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type CalculateStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalStats    map[string]float64     `protobuf:"bytes,1,rep,name=final_stats,json=finalStats,proto3" json:"final_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // e.g. {"HP": 5000, "ATTACK": 350, "DEFENSE": 200, "CRIT_RATE": 15}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateStatsResponse) Reset() {
	*x = CalculateStatsResponse{}
	mi := &file_zzstat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateStatsResponse) ProtoMessage() {}

func (x *CalculateStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateStatsResponse.ProtoReflect.Descriptor instead.
func (*CalculateStatsResponse) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateStatsResponse) GetFinalStats() map[string]float64 {
	if x != nil {
		return x.FinalStats
	}
	return nil
}

type CombatStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Level           int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Attack          float64                `protobuf:"fixed64,2,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense         float64                `protobuf:"fixed64,3,opt,name=defense,proto3" json:"defense,omitempty"`
	Dex             float64                `protobuf:"fixed64,4,opt,name=dex,proto3" json:"dex,omitempty"`
	CritRate        float64                `protobuf:"fixed64,5,opt,name=crit_rate,json=critRate,proto3" json:"crit_rate,omitempty"`
	CritDamageBonus float64                `protobuf:"fixed64,6,opt,name=crit_damage_bonus,json=critDamageBonus,proto3" json:"crit_damage_bonus,omitempty"`
	AccModifiers    float64                `protobuf:"fixed64,7,opt,name=acc_modifiers,json=accModifiers,proto3" json:"acc_modifiers,omitempty"`
	DodgeModifiers  float64                `protobuf:"fixed64,8,opt,name=dodge_modifiers,json=dodgeModifiers,proto3" json:"dodge_modifiers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CombatStats) Reset() {
	*x = CombatStats{}
	mi := &file_zzstat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStats) ProtoMessage() {}

func (x *CombatStats) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStats.ProtoReflect.Descriptor instead.
func (*CombatStats) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{3}
}

func (x *CombatStats) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CombatStats) GetAttack() float64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *CombatStats) GetDefense() float64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *CombatStats) GetDex() float64 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *CombatStats) GetCritRate() float64 {
	if x != nil {
		return x.CritRate
	}
	return 0
}

func (x *CombatStats) GetCritDamageBonus() float64 {
	if x != nil {
		return x.CritDamageBonus
	}
	return 0
}

func (x *CombatStats) GetAccModifiers() float64 {
	if x != nil {
		return x.AccModifiers
	}
	return 0
}

func (x *CombatStats) GetDodgeModifiers() float64 {
	if x != nil {
		return x.DodgeModifiers
	}
	return 0
}

type CalculateDamageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Attacker        *CombatStats           `protobuf:"bytes,1,opt,name=attacker,proto3" json:"attacker,omitempty"`
	Defender        *CombatStats           `protobuf:"bytes,2,opt,name=defender,proto3" json:"defender,omitempty"`
	SkillMultiplier float64                `protobuf:"fixed64,3,opt,name=skill_multiplier,json=skillMultiplier,proto3" json:"skill_multiplier,omitempty"`
	SkillFlatDamage float64                `protobuf:"fixed64,4,opt,name=skill_flat_damage,json=skillFlatDamage,proto3" json:"skill_flat_damage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateDamageRequest) Reset() {
	*x = CalculateDamageRequest{}
	mi := &file_zzstat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDamageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDamageRequest) ProtoMessage() {}

func (x *CalculateDamageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDamageRequest.ProtoReflect.Descriptor instead.
func (*CalculateDamageRequest) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateDamageRequest) GetAttacker() *CombatStats {
	if x != nil {
		return x.Attacker
	}
	return nil
}

func (x *CalculateDamageRequest) GetDefender() *CombatStats {
	if x != nil {
		return x.Defender
	}
	return nil
}

func (x *CalculateDamageRequest) GetSkillMultiplier() float64 {
	if x != nil {
		return x.SkillMultiplier
	}
	return 0
}

func (x *CalculateDamageRequest) GetSkillFlatDamage() float64 {
	if x != nil {
		return x.SkillFlatDamage
	}
	return 0
}

type CalculateDamageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHit         bool                   `protobuf:"varint,1,opt,name=is_hit,json=isHit,proto3" json:"is_hit,omitempty"`
	Damage        int32                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	IsCrit        bool                   `protobuf:"varint,3,opt,name=is_crit,json=isCrit,proto3" json:"is_crit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDamageResponse) Reset() {
	*x = CalculateDamageResponse{}
	mi := &file_zzstat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDamageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDamageResponse) ProtoMessage() {}

func (x *CalculateDamageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zzstat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDamageResponse.ProtoReflect.Descriptor instead.
func (*CalculateDamageResponse) Descriptor() ([]byte, []int) {
	return file_zzstat_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateDamageResponse) GetIsHit() bool {
	if x != nil {
		return x.IsHit
	}
	return false
}

func (x *CalculateDamageResponse) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CalculateDamageResponse) GetIsCrit() bool {
	if x != nil {
		return x.IsCrit
	}
	return false
}

var File_zzstat_proto protoreflect.FileDescriptor

const file_zzstat_proto_rawDesc = "" +
	"\n" +
	"\fzzstat.proto\x12\x06zzstat\"\xa7\x01\n" +
	"\fStatModifier\x12\x12\n" +
	"\x04stat\x18\x01 \x01(\tR\x04stat\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_id\x18\x06 \x01(\tR\bsourceId\"n\n" +
	"\x15CalculateStatsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x122\n" +
	"\tmodifiers\x18\x02 \x03(\v2\x14.zzstat.StatModifierR\tmodifiers\"\xa8\x01\n" +
	"\x16CalculateStatsResponse\x12O\n" +
	"\vfinal_stats\x18\x01 \x03(\v2..zzstat.CalculateStatsResponse.FinalStatsEntryR\n" +
	"finalStats\x1a=\n" +
	"\x0fFinalStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xfe\x01\n" +
	"\vCombatStats\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x16\n" +
	"\x06attack\x18\x02 \x01(\x01R\x06attack\x12\x18\n" +
	"\adefense\x18\x03 \x01(\x01R\adefense\x12\x10\n" +
	"\x03dex\x18\x04 \x01(\x01R\x03dex\x12\x1b\n" +
	"\tcrit_rate\x18\x05 \x01(\x01R\bcritRate\x12*\n" +
	"\x11crit_damage_bonus\x18\x06 \x01(\x01R\x0fcritDamageBonus\x12#\n" +
	"\racc_modifiers\x18\a \x01(\x01R\faccModifiers\x12'\n" +
	"\x0fdodge_modifiers\x18\b \x01(\x01R\x0edodgeModifiers\"\xd1\x01\n" +
	"\x16CalculateDamageRequest\x12/\n" +
	"\battacker\x18\x01 \x01(\v2\x13.zzstat.CombatStatsR\battacker\x12/\n" +
	"\bdefender\x18\x02 \x01(\v2\x13.zzstat.CombatStatsR\bdefender\x12)\n" +
	"\x10skill_multiplier\x18\x03 \x01(\x01R\x0fskillMultiplier\x12*\n" +
	"\x11skill_flat_damage\x18\x04 \x01(\x01R\x0fskillFlatDamage\"a\n" +
	"\x17CalculateDamageResponse\x12\x15\n" +
	"\x06is_hit\x18\x01 \x01(\bR\x05isHit\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x05R\x06damage\x12\x17\n" +
	"\ais_crit\x18\x03 \x01(\bR\x06isCrit2^\n" +
	"\vStatService\x12O\n" +
	"\x0eCalculateStats\x12\x1d.zzstat.CalculateStatsRequest\x1a\x1e.zzstat.CalculateStatsResponse2c\n" +
	"\rCombatService\x12R\n" +
	"\x0fCalculateDamage\x12\x1e.zzstat.CalculateDamageRequest\x1a\x1f.zzstat.CalculateDamageResponseB=Z;github.com/singoesdeep/zzrpg/backend/internal/statclient/pbb\x06proto3"

var (
	file_zzstat_proto_rawDescOnce sync.Once
	file_zzstat_proto_rawDescData []byte
)

func file_zzstat_proto_rawDescGZIP() []byte {
	file_zzstat_proto_rawDescOnce.Do(func() {
		file_zzstat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zzstat_proto_rawDesc), len(file_zzstat_proto_rawDesc)))
	})
	return file_zzstat_proto_rawDescData
}

var file_zzstat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_zzstat_proto_goTypes = []any{
	(*StatModifier)(nil),            // 0: zzstat.StatModifier
	(*CalculateStatsRequest)(nil),   // 1: zzstat.CalculateStatsRequest
	(*CalculateStatsResponse)(nil),  // 2: zzstat.CalculateStatsResponse
	(*CombatStats)(nil),             // 3: zzstat.CombatStats
	(*CalculateDamageRequest)(nil),  // 4: zzstat.CalculateDamageRequest
	(*CalculateDamageResponse)(nil), // 5: zzstat.CalculateDamageResponse
	nil,                             // 6: zzstat.CalculateStatsResponse.FinalStatsEntry
}
var file_zzstat_proto_depIdxs = []int32{
	0, // 0: zzstat.CalculateStatsRequest.modifiers:type_name -> zzstat.StatModifier
	6, // 1: zzstat.CalculateStatsResponse.final_stats:type_name -> zzstat.CalculateStatsResponse.FinalStatsEntry
	3, // 2: zzstat.CalculateDamageRequest.attacker:type_name -> zzstat.CombatStats
	3, // 3: zzstat.CalculateDamageRequest.defender:type_name -> zzstat.CombatStats
	1, // 4: zzstat.StatService.CalculateStats:input_type -> zzstat.CalculateStatsRequest
	4, // 5: zzstat.CombatService.CalculateDamage:input_type -> zzstat.CalculateDamageRequest
	2, // 6: zzstat.StatService.CalculateStats:output_type -> zzstat.CalculateStatsResponse
	5, // 7: zzstat.CombatService.CalculateDamage:output_type -> zzstat.CalculateDamageResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zzstat_proto_init() }
func file_zzstat_proto_init() {
	if File_zzstat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zzstat_proto_rawDesc), len(file_zzstat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_zzstat_proto_goTypes,
		DependencyIndexes: file_zzstat_proto_depIdxs,
		MessageInfos:      file_zzstat_proto_msgTypes,
	}.Build()
	File_zzstat_proto = out.File
	file_zzstat_proto_goTypes = nil
	file_zzstat_proto_depIdxs = nil
}
